package test12_1;

import java.util.HashMap;

public class SeatingChartTest {
    public static void main(String[] args) {
        HashMap<Integer, String> stuMap = new HashMap<Integer, String>();
        stuMap.put(1, "阮倩瑜");
        stuMap.put(2, "汤碧瑜");
        stuMap.put(3, "唐海萍");
        stuMap.put(4, "范盈盈");
        stuMap.put(5, "赖熙芝");
        stuMap.put(6, "冯家慧");
        stuMap.put(7, "甘伟杰");
        stuMap.put(8, "郑元峻");
        stuMap.put(9, "文雅");
        stuMap.put(10, "邱艳珊");
        stuMap.put(11, "吴嘉莹");
        stuMap.put(12, "潘慧妍");
        stuMap.put(13, "尹婷");
        stuMap.put(14, "洪铭言");
        stuMap.put(15, "刘柏君");
        stuMap.put(16, "林靖杭");
        stuMap.put(17, "谢蕙伊");
        stuMap.put(18, "蔡小熳");
        stuMap.put(19, "石海珍");
        stuMap.put(20, "姚星宇");
        stuMap.put(21, "张国彬");
        stuMap.put(22, "李炎涛");
        stuMap.put(23, "李倩怡");
        stuMap.put(24, "张卿恺");
        stuMap.put(25, "黄浩汶");
        stuMap.put(26, "陈浩");
        stuMap.put(27, "胡迦南");
        stuMap.put(28, "陈家乐");
        stuMap.put(29, "张政康");
        stuMap.put(30, "梁钰明");
        stuMap.put(31, "钟晓彤");
        stuMap.put(32, "罗心莹");
        stuMap.put(33, "曾芷熙");
        stuMap.put(34, "李俐瑶");
        stuMap.put(35, "张观业");
        stuMap.put(36, "李鑫杰");
        stuMap.put(37, "朱锐豪");
        stuMap.put(38, "范家聪");
        stuMap.put(39, "唐佳颖");
        stuMap.put(40, "何嘉慧");
        stuMap.put(41, "周婉倩");
        stuMap.put(42, "黄浩伦");
        stuMap.put(43, "郝梓慧");
        stuMap.put(44, "黄健");
        stuMap.put(45, "莫烨沂");
        stuMap.put(46, "刘姝含");
        stuMap.put(47, "李芷柔");
        stuMap.put(48, "朱慧赞");
        stuMap.put(49, "陈锦涛");
        stuMap.put(50, "覃佩怡");
        stuMap.put(51, "夏子言");
        stuMap.put(52, "潘泳欣");
        stuMap.put(53, "刘慧影");
        stuMap.put(54, "林子晴");
        stuMap.put(55, "肖晓晴");
        stuMap.put(56, "李洁怡");
        stuMap.put(57, "阮学闵");
        HashMap<Integer, Integer> genderMap = new HashMap<Integer, Integer>();
        genderMap.put(1, 1);
        genderMap.put(2, 1);
        genderMap.put(3, 1);
        genderMap.put(4, 1);
        genderMap.put(5, 1);
        genderMap.put(6, 1);
        genderMap.put(7, 0);
        genderMap.put(8, 0);
        genderMap.put(9, 1);
        genderMap.put(10, 1);
        genderMap.put(11, 1);
        genderMap.put(12, 1);
        genderMap.put(13, 1);
        genderMap.put(14, 0);
        genderMap.put(15, 0);
        genderMap.put(16, 1);
        genderMap.put(17, 1);
        genderMap.put(18, 1);
        genderMap.put(19, 1);
        genderMap.put(20, 0);
        genderMap.put(21, 0);
        genderMap.put(22, 0);
        genderMap.put(23, 1);
        genderMap.put(24, 0);
        genderMap.put(25, 0);
        genderMap.put(26, 0);
        genderMap.put(27, 0);
        genderMap.put(28, 0);
        genderMap.put(29, 0);
        genderMap.put(30, 0);
        genderMap.put(31, 1);
        genderMap.put(32, 1);
        genderMap.put(33, 1);
        genderMap.put(34, 1);
        genderMap.put(35, 0);
        genderMap.put(36, 0);
        genderMap.put(37, 0);
        genderMap.put(38, 0);
        genderMap.put(39, 1);
        genderMap.put(40, 1);
        genderMap.put(41, 1);
        genderMap.put(42, 0);
        genderMap.put(43, 1);
        genderMap.put(44, 0);
        genderMap.put(45, 1);
        genderMap.put(46, 1);
        genderMap.put(47, 1);
        genderMap.put(48, 1);
        genderMap.put(49, 0);
        genderMap.put(50, 1);
        genderMap.put(51, 1);
        genderMap.put(52, 1);
        genderMap.put(53, 1);
        genderMap.put(54, 1);
        genderMap.put(55, 1);
        genderMap.put(56, 1);
        genderMap.put(57, 1);
        int[] endOfGroups = new int[]{1, 3, 6, 8};
        SeatingChart seatingChart = new SeatingChart(9, stuMap.size(), stuMap, genderMap, endOfGroups);
        seatingChart.startArrangement();
        seatingChart.showChart();
    }
}
